name: Wake Up Render Service

on:
  schedule:
    # This runs at 5:00 AM UTC every day
    - cron: '0 5 * * *'

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the web service to wake it up
        run: curl -s https://smart-tracker-su0u.onrender.com > /dev/null